== Camel Example Main Groovy

This example shows how to run Camel standalone (YAML routes) with Groovy scripts
for small functions and DTO classes.

The Groovy source is located in `src/main/resources/camel-groovy`, which
are pre-compiled on startup.

This allows Camel routes to use the Groovy classes (as if they were Java classes).
The route will then transform a JSon file into a DTO class using Jackson, and then
enrich the DTO based on some business logic that are inlined Groovy script in the Camel route.

=== Build

First compile the example by executing:

[source,sh]
----
$ mvn compile
----

=== How to run

You can run this example using

[source,sh]
----
$ mvn camel:run
----

=== How to configure for Camel Textual Route debugging

Several IDEs are providing support for Camel Textual Route debugging. To enable this possibility, you need to launch this example with the profile `camel.debug`.

[source,sh]
----
$ mvn camel:run -Pcamel.debug
----

This profile can also be activated with camel.debug property set to true. For instance, by setting the property from command-line:

[source,sh]
----
$ mvn camel:run -Dcamel.debug=true
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
