== Camel Example Kamelet Chuck Norris

=== Introduction

This example shows how to use an official Kamelet from the
https://camel.apache.org/camel-kamelets/next/[Kamelets Catalog]
in a traditional Maven-based Camel application.

The example uses the
https://camel.apache.org/camel-kamelets/next/chuck-norris-source.html[Chuck Norris Source]
Kamelet which periodically gets a joke from the Chuck Norris internet database.

The official Kamelets are included as a Maven dependency by adding the `camel-kamelets`
JAR to the `pom.xml`. Kamelets are then auto-discovered from the classpath at runtime.

NOTE: The `camel-kamelets` JAR only contains the Kamelet YAML definitions. You must also
add the Camel component dependencies that the Kamelet uses internally
(e.g. `camel-timer`, `camel-http`, `camel-jsonpath` for the Chuck Norris Kamelet).

The Camel route is defined in `my-route.camel.yaml` using the YAML DSL and logs
the joke to the console.

=== Build

You will need to compile this example first:

[source,sh]
----
$ mvn compile
----

=== Run

You can run this example using

[source,sh]
----
$ mvn camel:run
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
