== Camel Example Main YAML

This example shows how to run Camel standalone (YAML routes) via the built-in Main class.

The route is located in `src/main/resources/routes` as an YAML file.

This example has been enabled with live reload, so while the Camel
application is running, then you can edit the route in the YAML file,
and when saved Camel will auto update the route(s).

The application is configured in the `application.properties` file.

=== Build

First compile the example by executing:

[source,sh]
----
$ mvn compile
----

=== How to run

You can run this example using

[source,sh]
----
$ mvn camel:run
----

=== How to configure for Camel Textual Route debugging

Several IDEs are providing support for Camel Textual Route debugging. To enable this possibility, you need to launch this example with the profile `camel.debug`.

[source,sh]
----
$ mvn camel:run -Pcamel.debug
----

This profile can also be activated with camel.debug property set to true. For instance, by setting the property from command-line:

[source,sh]
----
$ mvn camel:run -Dcamel.debug=true
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
