== Embedded ActiveMQ Broker with Camel running in Apache Tomcat

=== Introduction

This example shows how you can embed Apache ActiveMQ Broker and Camel in
a web application, which can run on Apache Tomcat or other web
containers.

This example embeds ActiveMQ Broker and a Camel application, which will
continuously send a message per second to an inbox queue. Then another
Camel route will route messages from the inbox to the outbox queue.

==== Camel component used in this example

* camel-core
* camel-jms
* camel-spring

=== Build

You will need to build this example first:

[source,sh]
----
$ mvn package
----

=== Run

Which will create a `.war` file in the target directly.

You can then deploy this `.war` file in any web container such as
Apache Tomcat, by copying the `.war` file to its `/webapps`
directory manually or via the following command (assuming that the
environment variable `TOMCAT_HOME` has been set properly):

[source,sh]
----
$ mv target/camel-example-activemq-tomcat.war ${TOMCAT_HOME}/webapps/
----

=== Configuration

The ActiveMQ broker is configured in the
`src/main/resources/broker.xml` file. The Camel application is configured in the
`src/main/resources/camel-context.xml` file.

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
