== Minio Example - CDI

=== Introduction

This example illustrates the integration between Camel, CDI and Minio.

The `+camel-cdi+` and `+camel-minio+` components used in this
example.

Don't forget to add your bucket name, and your credentials in the
resources/minio_key.properties file before compiling. The bucketName in the route is  `bucketName'.

=== Build

You can build this example using:

[source,sh]
----
$ mvn package
----

=== Run

You can run this example using:

[source,sh]
----
$ mvn camel:run
----

When the Camel application runs, you should see the files from your bucket
downloaded and saved into target/minio_out directory with their respective
filename.

The Camel application can be stopped pressing ctrl+c in the shell.

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
