== Camel Example Kamelet Main

=== Introduction

This example shows how to use ready to use Kamelets that you can find at the
https://camel.apache.org/camel-kamelets/next/[Camel Kamelet Catalog].

The application is run with `KameletMain` class from camel-kamelet-main JAR.
This makes it easy to run Camel standalone with Kamelet that can be automatically
downloaded from GitHub, and to use YAML DSL for creating Camel routes that use the Kamelets.
The example has no Java code at all.

A Camel routes is _coded_ in the `my-route.yaml` file using the YAML DSL that uses the Kamelet,
and log the result from the Kamelet to the console.

=== Build

You will need to compile this example first:

[source,sh]
----
$ mvn compile
----

=== Run

You can run this example using

[source,sh]
----
$ mvn camel:run
----

The application is also built as a _fat jar_ (see `pom.xml`), which you can run with

[source,sh]
----
$ mvn package -DskipTests
$ java -jar target/camel-example-kamelet-main-jar-with-dependencies.jar
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
