== Camel Example Kamelet YAML

=== Introduction

This example shows how to use ready to use Kamelets you can find at the
https://camel.apache.org/camel-kamelets/latest/[Camel Kamelet Catalog].

We are using the _Earthquake Source_ Kamelet which we load from github at startup
with the `camel-resourceresolver-github` JAR.

You can also download the Kamelet YAML file from github and save into `src/main/resources/kamelets` folder,
which the `camel-kamelet` component would automatic load from. If you do that then remove the
`camel.component.kamelet.location=github:apache:camel-kamelets` from the `application.properties` file.

Before the Kamelet is ready to use, we must add the needed Camel components
(you can find the list inside the kamelet YAML file) to the Maven `pom.xml` file.

A Camel routes is _coded_ in the `my-route.yaml` file using the YAML DSL that uses the Kamelet,
and log the result from the Kamelet to the console.

The example has no Java code at all, and is started via Camel's own `Main` class from `camel-main` JAR.

=== Build

You will need to compile this example first:

[source,sh]
----
$ mvn compile
----

=== Run

You can run this example using

[source,sh]
----
$ mvn camel:run
----

The application is also built as a _fat jar_ (see `pom.xml`), which you can run with

[source,sh]
----
$ mvn package
$ java -jar target/camel-example-kamelet-yaml-3.11.0-jar-with-dependencies.jar
----


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
