== Camel Hazelcast route on Kubernetes cluster

This quickstart run in a Java standalone container, using Spring with
Apache Camel (Hazelcast component).

This quickstart is based on the Kubernetes example here:
https://github.com/kubernetes/kubernetes/tree/master/examples/storage/hazelcast

This example is based on:

* Minikube (Kubernetes version >= 1.5) or CRC (Openshift >= 4.x)
* https://github.com/eclipse/jkube[Eclipse JKube]

First thing you’ll need to do is preparing the environment.

Once your Minikube node is up and running you’ll need to run the
following command. In your `src/main/jkube/raw`` folder you’ll
find two yaml files. There are for your hazelcast `Service` and
`Deployment`. Eclipse JKube would pick this up during it's
resource generation phase and apply it during deploy phase.

....
camel-example-hazelcast-kubernetes : $ tree src/main/jkube/
src/main/jkube/
└── raw
    ├── hazelcast-deployment.yaml
    └── hazelcast-service.yaml

1 directory, 2 files
....

=== Building and running

Navigate to the project folder and the example can be built with

==== Kubernetes (Minikube)
....
$ mvn clean -Pkubernetes-install k8s:deploy
....

When the example runs in Eclipse JKube, you can use the Kubectl command tool
to inspect the status

To list all the running pods on Minikube:

....
$ kubectl get pods
....

Then find the name on Minikube of the pod that runs this quickstart, and
output the logs from the running pods with:

....
$ kubectl logs <name of pod>
....

==== OpenShift (CRC)

To list all the running pods on CRC:

....
$ mvn clean -Popenshift-install oc:deploy
....

When the example runs in Eclipse JKube, you can use the Kubectl command tool
to inspect the status

To list all the running pods on Minikube:

....
$ oc get pods
....

Then find the name on CRC of the pod that runs this quickstart, and
output the logs from the running pods with:

....
$ oc logs <name of pod>
....

and you should see something like this:

....
Feb 19, 2018 7:18:39 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [someGroup] [3.9.2] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/172.17.0.8:41011->hazelcast/10.102.1.255:5701}, remoteEndpoint=[172.17.0.4]:5701, lastReadTime=2018-02-19 07:18:39.464, lastWriteTime=2018-02-19 07:18:39.424, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9.3} as owner with principal ClientPrincipal{uuid='0daabf2b-0b33-4a55-8453-683d7fa0436e', ownerUuid='59045d20-faf3-4a73-b4de-e8036f4b7caa'}
Feb 19, 2018 7:18:39 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [someGroup] [3.9.2] HazelcastClient 3.9.2 (20180103 - 17e4ec3) is CLIENT_CONNECTED
Feb 19, 2018 7:18:39 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: hz.client_0 [someGroup] [3.9.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2018-02-19 07:18:39,582 [main           ] INFO  SpringCamelContext             - Apache Camel 2.21.0-SNAPSHOT (CamelContext: camel-1) is starting
2018-02-19 07:18:39,583 [main           ] INFO  ManagedManagementStrategy      - JMX is enabled
2018-02-19 07:18:39,842 [main           ] INFO  DefaultTypeConverter           - Type converters loaded (core: 193, classpath: 1)
2018-02-19 07:18:40,028 [main           ] INFO  SpringCamelContext             - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
Feb 19, 2018 7:18:40 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [someGroup] [3.9.2] Authenticated with server [172.17.0.6]:5701, server version:3.9.3 Local address: /172.17.0.8:46877
Feb 19, 2018 7:18:40 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [someGroup] [3.9.2] Authenticated with server [172.17.0.5]:5701, server version:3.9.3 Local address: /172.17.0.8:36763
Feb 19, 2018 7:18:40 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [someGroup] [3.9.2] Authenticated with server [172.17.0.7]:5701, server version:3.9.3 Local address: /172.17.0.8:34969
2018-02-19 07:18:40,837 [main           ] INFO  SpringCamelContext             - Route: route1 started and consuming from: timer://foo?period=5000
2018-02-19 07:18:40,838 [main           ] INFO  SpringCamelContext             - Route: route2 started and consuming from: hazelcast-topic://foo
2018-02-19 07:18:40,838 [main           ] INFO  SpringCamelContext             - Total 2 routes, of which 2 are started
2018-02-19 07:18:40,840 [main           ] INFO  SpringCamelContext             - Apache Camel 2.21.0-SNAPSHOT (CamelContext: camel-1) started in 1.258 seconds
2018-02-19 07:18:40,843 [main           ] INFO  DefaultLifecycleProcessor      - Starting beans in phase 2147483646
2018-02-19 07:18:41,846 [2 - timer://foo] INFO  route1                         - Producer side: Sending data to Hazelcast topic..
2018-02-19 07:18:41,886 [lient_0.event-3] INFO  route2                         - Consumer side: Detected following action: received
2018-02-19 07:18:46,840 [2 - timer://foo] INFO  route1                         - Producer side: Sending data to Hazelcast topic..
2018-02-19 07:18:46,842 [lient_0.event-3] INFO  route2                         - Consumer side: Detected following action: received
2018-02-19 07:18:51,840 [2 - timer://foo] INFO  route1                         - Producer side: Sending data to Hazelcast topic..
2018-02-19 07:18:51,842 [lient_0.event-3] INFO  route2                         - Consumer side: Detected following action: received
....

=== Cleanup

Run following to undeploy on Minikube

....
$ mvn -Pkubernetes-install k8s:undeploy
....

Run following to undeploy on CRC

....
$ mvn -Popenshift-install oc:undeploy
....

Make sure no pod is running

....
$ kubectl get pods
No resources found.
....

....
$ oc get pods
No resources found.
....

=== Help and contributions

If you hit any problem using Camel or have some feedback, 
then please https://camel.apache.org/support.html[let us know].

We also love contributors, 
so https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
