== Camel Example Route Loader with Java

This example shows how Camel is capable of loading routes during startup using the new route loader system.
The route loader has support for loading routes in XML and Java (other languages to be added).

This is the feature that was first developed as part of Camel K which has evolved to be a core
part of Camel.

The Java route loader is using `camel-joor` component which has the support for dynamic compiling Java source.

The example has a Java route in the `src/main/resources/myroutes` directory. This route is a java file,
but the file is not part of the regular source code and is therefore not compiled with the regular Java compiler.
The route is loaded by Camels route loader and dynamic compiled via `camel-joor` during startup of Camel.

=== How to run

You can run this example using

    mvn camel:run

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
