== Camel Example Route Template

This examples shows how to use Route Templates (parameterized routes) to specify a skeleton route
which can be used for creating and adding new routes via parameters.

The route template is defined via Java or XML DSL (RouteBuilder) in the `MyRouteTemplates.java` source file.

The `application.properties` is used to create two routes from the template using different set of parameters.

An alternative to create routes is from Java which is done in the `MyTemplateBuilder.java` class.
See the `MyApplication.java` where you can change the source to use java instead of property file for the template parameters.

The example runs standalone via Camel Main in the `MyApplication.java` source file.

=== Build

You will need to compile this example first:

----
$ mvn compile
----

=== How to run

You can run this example using

----
$ mvn camel:run
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
